export const categories = [
  "Technology",
  "Business",
  "Lifestyle",
  "Health",
  "Travel",
  "Food",
  "Education",
  "Finance",
  "Entertainment",
  "Science",
  "Art & Design",
  "Politics",
  "Sports",
  "Culture",
  "Fashion",
  
  "Parenting & Family",
  "Environment & Sustainability",
  "Gaming",
  "Marketing & Social Media",
  "Music",
  "Literature",
  "History",
  "Career & Jobs",
  "Automotive",
  "Real Estate",
  "Pets & Animals",
  "Self-Care & Wellness",
  "Startups & Entrepreneurship",
  "Philosophy",
  "Cybersecurity",
  "Law & Legal",
  "Public Speaking & Communication Skills",
  "Graphic Design & Illustration",
  "Blockchain & Cryptocurrency",
  "E-commerce",

];
